dist: trusty
sudo: required

language: python

python:
    - "2.7"
    - "3.6"

cache: pip

services:
    - rabbitmq
    - postgresql
    - docker

addons:
    # make sure the path in .ci/test_script.sh matches the version requested here
    postgresql: "9.6"

    apt:
        packages:
            - postgresql-server-dev-9.6
            - texlive-base
            - texlive-generic-recommended
            - texlive-fonts-recommended
            - texlive-latex-base
            - texlive-latex-recommended
            - texlive-latex-extra
            - dvipng
            - dvidvi
            - graphviz

before_install:
    # We need to replace `TRAVIS_HOME` with `HOME` because the former won't be set when SSH'ing to localhost on the
    # the Travis machine, causing certain scripts sourced in the `.bashrc` to fail
    - sed -i 's/TRAVIS_HOME/HOME/g' /home/travis/.travis/job_stages
    # This is needed for the SSH tests (being able to ssh to localhost)
    # And will also be used for the docker test
    - ssh-keygen -t rsa -N "" -f "${HOME}/.ssh/id_rsa"
    - cp "${HOME}/.ssh/id_rsa.pub" "${HOME}/.ssh/authorized_keys"
    - ssh-keyscan -H localhost >> "${HOME}/.ssh/known_hosts"

    # Needed to have 'locate' work properly
    - sudo updatedb
    - .ci/prep_ssh.sh

    # Build the docker image if needed
    - .ci/before_install.sh

install:
    # Upgrade pip setuptools and wheel to be able to run the next command
    - pip install -U pip==18.1 wheel setuptools coveralls
    - pip install coveralls
    # Install AiiDA with some optional dependencies
    - if [ "$TEST_TYPE" == "docs" ]; then pip install . && pip install -r docs/requirements_for_rtd.txt; else pip install --no-cache-dir .[all]; fi

env:
    ## Build matrix to test both backends, and the docs
    ## I still let it create the test backend for django
    ## also when building the docs
    ## because otherwise the code would complain. Also, I need latex.
    - TEST_TYPE="pre-commit"
    - TEST_AIIDA_BACKEND=django TEST_TYPE="docs"
    - TEST_AIIDA_BACKEND=django TEST_TYPE="tests"
    - TEST_AIIDA_BACKEND=sqlalchemy TEST_TYPE="tests"
    - TEST_TYPE="conda"

before_script:
    - .ci/setup_profiles.sh
    - .ci/before_script.sh

script: .ci/test_script.sh


after_success:
  # upload coverage report to coveralls.io
  - if [ "$TEST_TYPE" == "tests" ]; then coveralls; fi

git:
  depth: 3

jobs:
    include:
        - stage: deploy
          addons: skip
          python: 3.6
          before_install: skip
          install: skip
          before_script: skip
          script: skip
          env: skip
          after_deploy:
            - echo "Deployed $GIT_TAG"
            - echo "We'll hook up some things after the future"
          deploy: &pypi
              provider: pypi
              skip_existing: true
              username: aiida-bot
              password:
                  secure: LAWil3MvA5Lu+9W1DN7To+DV3lFoH+9U2BB+eg8ikRrvTCoFvgF1tgFtE0lmRd2aH/YHbtXDEfiWCEAZPZIdphzOLrYR9WlBkrQrDPh8lzN7ClDoEiMjgwg6Pz65aSYrMTxegUfDEoIXMJqjl2o9xQ2/g13/oZu8FhkhlFl/taPsaf+Wo777HH8BXss0zsIDMgHMO29uqyg2J7sTyR8FOIMGfoESIuOIkII7AktMxNC8Ys2+PLOkoFI7eyHN1RUrsD+3mDjm8IJsnRX+B4R068cDLGfLLRxNCpEwydEjEwnm7YFa9IjxLRLKySeE5Im6USQA4LkaH/gJ/fl9jpDta81nqYK8OdVcJrO8Z9VAFNfDRW46PhxC46k3uQy7ddqQ4vAy+mKP8+B3S7qACnCnPHOvTxJ+rkrYhRN83INjJ2/7lVPkUQoscy4DiWyKK0DeBRhs5ZD2P7O/ZGB/6fA8m8ZSnzTB+hKwA+C+9/86By/r2w0xFQ/W0uI1C+uuoupSkrACqxHEsUFiS5M4Paf6EIpUUS86BGN2FsiXhsgMRKxfiGxtVIvTm8v3b7fGThLquv9jnk9j+boQyRc4cEGSy5xPYz+HumoF0OlbTEptcbQguAhIQHCHKjwjkEhrB8rK+iZquGMYPFP9a7N54RBMBySW465rMG7+ML0pHJPBTuU=
              on:
                  repo: odarbelaeze/aiida_core
                  branch: automated-publishing
                  tags: true
                  condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+(a|b|rc)?[0-9]*$"