dist: trusty
sudo: required

language: python

python:
    - "2.7"
    - "3.6"

cache: pip

services:
    - rabbitmq
    - postgresql
    - docker

addons:
    # make sure the path in .ci/test_script.sh matches the version requested here
    postgresql: "9.6"

    apt:
        packages:
            - postgresql-server-dev-9.6
            - texlive-base
            - texlive-generic-recommended
            - texlive-fonts-recommended
            - texlive-latex-base
            - texlive-latex-recommended
            - texlive-latex-extra
            - dvipng
            - dvidvi
            - graphviz

before_install:
    # We need to replace `TRAVIS_HOME` with `HOME` because the former won't be set when SSH'ing to localhost on the
    # the Travis machine, causing certain scripts sourced in the `.bashrc` to fail
    - sed -i 's/TRAVIS_HOME/HOME/g' /home/travis/.travis/job_stages
    # This is needed for the SSH tests (being able to ssh to localhost)
    # And will also be used for the docker test
    - ssh-keygen -t rsa -N "" -f "${HOME}/.ssh/id_rsa"
    - cp "${HOME}/.ssh/id_rsa.pub" "${HOME}/.ssh/authorized_keys"
    - ssh-keyscan -H localhost >> "${HOME}/.ssh/known_hosts"

    # Needed to have 'locate' work properly
    - sudo updatedb
    - .ci/prep_ssh.sh

    # Build the docker image if needed
    - .ci/before_install.sh

install:
    # Upgrade pip setuptools and wheel to be able to run the next command
    - pip install -U pip==18.1 wheel setuptools coveralls
    - pip install coveralls
    # Install AiiDA with some optional dependencies
    - if [ "$TEST_TYPE" == "docs" ]; then pip install . && pip install -r docs/requirements_for_rtd.txt; else pip install --no-cache-dir .[all]; fi

env:
    ## Build matrix to test both backends, and the docs
    ## I still let it create the test backend for django
    ## also when building the docs
    ## because otherwise the code would complain. Also, I need latex.
    - TEST_TYPE="pre-commit"
    - TEST_AIIDA_BACKEND=django TEST_TYPE="docs"
    - TEST_AIIDA_BACKEND=django TEST_TYPE="tests"
    - TEST_AIIDA_BACKEND=sqlalchemy TEST_TYPE="tests"
    - TEST_TYPE="conda"

before_script:
    - .ci/setup_profiles.sh
    - .ci/before_script.sh

script: .ci/test_script.sh


after_success:
  # upload coverage report to coveralls.io
  - if [ "$TEST_TYPE" == "tests" ]; then coveralls; fi

git:
  depth: 3

jobs:
    include:
        - stage: deploy
          if: "tag =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+(a|b|rc)?[0-9]*$"
          services: ignore
          addons: skip
          python: 3.6
          before_install: skip
          install: skip
          before_script: skip
          script: skip
          env: ignore
          before_deploy:
            - echo "We'll deploy $TRAVIS_TAG"
          after_deploy:
            - echo "Deployed $TRAVIS_TAG"
            - echo "We'll hook up some things in the future"
          deploy: &pypi
              provider: pypi
              skip_existing: true
              username: aiida-bot
              password:
                  secure: jfeaZDbeWHbIhNQw0zY2gesJkkQyFjeaL+8z9hBR8q2qyZOAjNdq4eP26UvWLyc0cFAh/HjUGdDD2attatJ1ElBk7/20Db5u1LeXHBwxtPdFlH/VG/gv/OOXVTlrZaQcAFklvUnEBrbE47AEXev9SddPWauP26vfW9ZNw77Nl196Sxa47HFeaJus1T2ALBBf3bKgxRaPOZ7nA9cnPtyMharP+cYGfIZF3V7hhn7PqemLQscSXzE8hT66F8b3USJvUFSTxFfKRFoR8g7t+qsnf4V/FkTu+Tt+C+zLYF0hXprgnNYNJM8T4EiK7vFsPODh/UfUUP/BXI8Bx9QgGqVOr1ybxN3jLmwfjqiOeC4Un7Bqg9C3NChMB5ZKF8lwKa1vEqputT24LWUYpVY+UyQibm6LFAcZWw6mc2nLbnhme8MgCmg+wcpZj0JZCXrISJPW0g02e+U/gchn+jGGddYq2A1ENt/LK4SLPKCfkXvX+PrIPKQMEdssL16auIbB3gFF2XUfbuDXyCgD5BVBFjYV4axtobSDYBZPcfjKZP2w8oTZrWMhklbN9njvOyze8PGzVuAEF9C4JrPKDNpl6tt2u8AyETq2GOkS2a/Bw2GfVLaKCE/L2VQnzUNpuFBdMY3fh0LagsbP+3t+MQQFp2pmhWdSmoOOMLRUAwdGMDza03s=
              on:
                  repo: odarbelaeze/aiida_core
                  branch: automated-bublish-test
                  tags: true
